# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

Layout/IndentationWidth:
    Width: 4
    AllowedPatterns: ['^\s*module']

Layout/LineLength:
    Max: 100

Lint/UnusedMethodArgument:
    AutoCorrect: False

Metrics/AbcSize:
    Max: 25

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Max: 20

AllCops:
    NewCops: enable
